Repository jenkinsci/authentication-tokens-plugin, pull requests merged in 2020-06, with the labels that each got.

#6 Migrate docs from Wiki to GitHub
  CHANGELOG.md
  README.md
  pom.xml
Labels: documentation

#7 Use parent POM 3.57
  pom.xml
Labels: dependencies

#8 Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .gitignore
  CHANGELOG.md
Labels: chore
